Update alune to set 13
TeamFightTacticsBots/Alune pull request #84
Opened 2024-11-21 15:57 UTC by catasdd

2024-11-21 16:18 UTC, Kyrluckechuck approved these changes
Makes enough sense assuming you tested the bot for the gameplay loop for the new season -- things like the new popups and such can cause issues if they change a lot between seasons

2024-11-21 17:02 UTC, akshualy requested changes
I just had the chance to check and there is no new second gamemode. I'm not sure if you understood, but dawn of heroes was not the normal TFT. Let's merge the traits into the normal traits class and leave the dawn of heroes code alone.

2024-11-21 17:02 UTC, akshualy commented on alune/images.py
>  class DawnOfHeroesTrait(StrEnum):
It would make sense to change this as well if there's a new second game mode

2024-11-21 21:24 UTC, catasdd commented
> I just had the chance to check and there is no new second gamemode. I'm not sure if you understood, but dawn of heroes was not the normal TFT. Let's merge the traits into the normal traits class and leave the dawn of heroes code alone.

I think I did it, but check it please.

2024-11-21 22:04 UTC, akshualy commented
> > I just had the chance to check and there is no new second gamemode. I'm not sure if you understood, but dawn of heroes was not the normal TFT. Let's merge the traits into the normal traits class and leave the dawn of heroes code alone.
> 
> I think I did it, but check it please.

looks better, but you still deleted the dawn of heroes stuff - i think that'll cause an error. running workflow to make sure

2024-11-21 22:34 UTC, catasdd commented
> > > I just had the chance to check and there is no new second gamemode. I'm not sure if you understood, but dawn of heroes was not the normal TFT. Let's merge the traits into the normal traits class and leave the dawn of heroes code alone.
> > 
> > 
> > I think I did it, but check it please.
> 
> looks better, but you still deleted the dawn of heroes stuff - i think that'll cause an error. running workflow to make sure
> 
> edit: yea as i thought, you're referring to an enum member that doesn't exist; you can replace [cls.DAWNBRINGER] with [] honestly

should I add dawnbringer stuff again or leave it like this?

2024-11-22 09:55 UTC, akshualy approved these changes

2024-11-22 09:55 UTC, akshualy commented
lgtm

2024-11-22 14:02 UTC, Kyrluckechuck reviewed
Could you run a `git checkout HEAD -- alune/images/traits/dawn_of_heroes/` to restore all of the dawn of heroes stuff since that isn't really related to the aim of the PR?

We may want to clean those up as well, but can do that separately

2024-11-22 17:53 UTC, subzdelta commented
Would like to know if someone can send the exe for the set 13 as I've ran some problems trying to merge it myself, thanks in advance!

2024-11-23 02:32 UTC, enbge commented
pls update ty

2024-11-23 11:12 UTC, merged